### ISSUE TITLE
本人菜鸟, 如果解释起来太麻烦, 就算了

### ISSUE THREAD

**Issue by lroronoazoro** [gucong3000/Sublime_Text_CN#1]
我想请问一下, 我不想安装node.js, 应该用哪个文件来汉化呢?如果解释起来太麻烦, 我就还是去安装node.js得了.....

**Comment by gucong3000** [comment]
打开sublime，点击“首选项”>“浏览插件”。会自动弹出一个文件夹，即这个目录。

**Comment by gucong3000** [comment]
已改为在根目录操作
